---

- name: Define custom settings
  ansible.builtin.template:
    src: "{{ item | basename }}.j2"
    dest: /etc/tower/{{ item }}
    owner: awx
    group: awx
    mode: "0640"
    backup: true
  loop:
    - SECRET_KEY
    - conf.d/db.py
    - conf.d/olam.py

- name: Configure cluster id via /etc/hosts  # noqa no-changed-when command-instead-of-module
  ansible.builtin.shell: |
    sed -i "/{{ olam_hostname }}/d" /etc/hosts
    echo "{{ ansible_default_ipv4['address'] }} {{ olam_hostname }}" >> /etc/hosts
  become: yes
  when: olam_hostname == 'olam.local'

- name: Make sure that '{{ olam_root }}' is writable  # noqa name[template]
  ansible.builtin.file:
    path: "{{ olam_root }}"
    owner: "{{ olam_owner }}"
    group: "{{ olam_group }}"
    mode: "0755"

- name: Podman system migrate
  ansible.builtin.command:
    cmd: podman system migrate
  become: yes
  become_user: awx
  changed_when: false
  when: olam_podman_system_migrate | default(true) | bool
  tags: molecule-notest

- name: Pull an image
  containers.podman.podman_image:
    name: container-registry.oracle.com/oracle_linux_automation_manager/olam-ee
  become: yes
  become_user: awx
  tags: molecule-notest
  environment:
    HTTPS_PROXY: "{{ olam_proxy | default('') }}"
    HTTP_PROXY: "{{ olam_proxy | default('') }}"

- name: Create receptor configuration from template
  ansible.builtin.template:
    src: receptor.conf.j2
    dest: /etc/receptor/receptor.conf
    owner: root
    group: root
    mode: "0644"

- name: Perform AWX migration
  ansible.builtin.command:
    cmd: awx-manage migrate
  become: yes
  become_user: awx
  register: __awx_migrate
  changed_when: "'No migrations to apply' not in __awx_migrate.stdout"

- name: Create admin user {{ olam_admin_username }}
  ansible.builtin.command:
    cmd: >-
      awx-manage createsuperuser
      --username {{ olam_admin_username }}
      --email {{ olam_admin_email }}
      --noinput
  become: yes
  become_user: awx
  register: __olam_user
  changed_when: "'That username is already taken' not in __olam_user.stderr"
  failed_when: __olam_user.rc > 1

- name: Set admin password for {{ olam_admin_username }}
  ansible.builtin.command:
    cmd: >-
      awx-manage update_password
      --username={{ olam_admin_username }}
      --password={{ olam_admin_password }}
  changed_when: false
  no_log: true
  become: yes
  become_user: awx
  tags: molecule-idempotence-notest

- name: Preload demo data
  ansible.builtin.command:
    cmd: >-
      awx-manage create_preload_data
  become: yes
  become_user: awx
  when: olam_demo_data | bool

- name: Get oauth token
  ansible.builtin.command:
    cmd: >-
      awx-manage create_oauth2_token
      --user {{ olam_admin_username }}
  changed_when: false
  register: __token

- name: Get instance info
  ansible.builtin.uri:
    url: "http://127.0.0.1/api/v2/instances/"
    method: GET
    headers:
      Authorization: "Bearer {{ __token.stdout }}"
      Content-Type: "application/json"
  register: __instances

- name: Make instances list
  ansible.builtin.set_fact:
    instances: >-
      {{ __instances.json.results | map(attribute='hostname') | list }}

- name: Get instance groups info
  ansible.builtin.uri:
    url: "http://127.0.0.1/api/v2/instance_groups/"
    method: GET
    headers:
      Authorization: "Bearer {{ __token.stdout }}"
      Content-Type: "application/json"
  register: __instance_groups

- name: Make instance group list
  ansible.builtin.set_fact:
    instance_groups: >-
      {
        {%- for g in __instance_groups.json.results -%}
        "{{ g.name }}": {{ g.policy_instance_list }}{{ '' if loop.last else ',' }}
        {%- endfor -%}
      }

- name: Configuration steps
  become: yes
  become_user: awx
  block:

    - name: Provision instance
      ansible.builtin.command:
        cmd: >-
          awx-manage provision_instance
          --hostname={{ olam_hostname }}
      changed_when: true
      when: "olam_hostname not in instances"

    - name: Register default execution_environments
      ansible.builtin.command:
        cmd: >-
          awx-manage register_default_execution_environments
      changed_when: "'changed: True' in __awx_manage.stdout"
      register: __awx_manage

    - name: Register queue 'default'
      ansible.builtin.command:
        cmd: >-
          awx-manage register_queue
          --queuename=default
          --hostnames={{ olam_hostname }}
      when:
        - instance_groups['default'] is defined
        - olam_hostname not in instance_groups['default']
      changed_when: true

    - name: Register queue 'controlplane'
      ansible.builtin.command:
        cmd: >-
          awx-manage register_queue
          --queuename=controlplane
          --hostnames={{ olam_hostname }}
      when:
        - instance_groups['default'] is defined
        - olam_hostname not in instance_groups['controlplane']
      changed_when: true

# - name: Update AWX settings
#   ansible.builtin.lineinfile:
#     path: /etc/tower/settings.py
#     regexp: "{{ item.key }} = .*"
#     line: "{{ item.key }} = \"{{ item.value }}\""
#   loop: "{{ olam_settings | dict2items }}"

- name: Copy SSL key
  ansible.builtin.copy:
    src: "{{ olam_ssl_key }}"
    dest: /etc/tower/tower.key
    remote_src: "{{ olam_ssl_remote_src | default(False) }}"
    mode: "0600"
  become: yes

- name: Copy SSL certificate
  ansible.builtin.copy:
    src: "{{ olam_ssl_certificate }}"
    dest: /etc/tower/tower.crt
    remote_src: "{{ olam_ssl_remote_src | default(False) }}"
    mode: "0644"
  become: yes

- name: Update nginx
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: "0644"
  notify: Restart nginx

- name: Disable IPv6
  ansible.builtin.replace:
    path: /etc/nginx/conf.d/ol-automation-manager-nginx.conf
    regexp: '^(\s +)(listen \[)'
    replace: '#\1\2'
  notify: Restart nginx
  when: olam_disable_ipv6 | bool

- name: Start the OLAM service
  ansible.builtin.service:
    name: ol-automation-manager
    enabled: yes
    state: started

# - name: Make postgresql reachable from external source
#   community.postgresql.postgresql_query:
#     db: "{{ olam_db_name }}"
#     query: ALTER USER {{ olam_db_user }} WITH PASSWORD '{{ olam_db_password }}';
#   become: yes
#   become_user: postgres
#   when: olam_db_external | bool
#   tags: molecule-idempotence-notest
