---

- name: Enable all default repositories
  community.general.ini_file:
    path: /etc/yum.repos.d/{{ item.file }}
    section: "{{ item.name }}"
    option: enabled
    value: "1"
    mode: "0644"
  vars:
    v: "{{ ansible_facts.distribution_major_version }}"
  loop:
    - { name: "ol{{ v }}_baseos_latest", file: "oracle-linux-ol{{ v }}.repo" }
    - { name: "ol{{ v }}_addons", file: "oracle-linux-ol{{ v }}.repo" }
    - { name: "ol{{ v }}_appstream", file: "oracle-linux-ol{{ v }}.repo" }
    - { name: "ol{{ v }}_codeready_builder", file: "oracle-linux-ol{{ v }}.repo" }
    # - { name: ol{{ v }}_distro_builder", file: "oracle-linux-ol{{ v }}.repo" }
    - { name: "ol{{ v }}_UEKR7", file: "uek-ol{{ v }}.repo" }
