---

- name: Install Oracle Linux Automation Manager repository
  ansible.builtin.dnf:
    name: oraclelinux-automation-manager-release-el{{ ansible_facts.distribution_major_version }}
    state: "{{ olam_package_state }}"

- name: Activate the required repository
  ansible.builtin.template:
    src: oraclelinux-automation-manager.repo.j2
    dest: /etc/yum.repos.d/oraclelinux-automation-manager-ol{{ ansible_facts.distribution_major_version }}.repo
    mode: "0644"
  notify: Dnf update cache

- name: Flush the handlers
  ansible.builtin.meta: flush_handlers

- name: Install the Oracle Linux Automation Manager package and any dependencies
  ansible.builtin.dnf:
    name: ol-automation-manager
    state: "{{ olam_package_state }}"
    disablerepo: epel
