---

- name: Test distro & version
  ansible.builtin.fail:
    msg: This role only works on OracleLinux 8
  when: ansible_distribution != "OracleLinux" and ansible_distribution_major_version != "8"

- name: Ensure all required variables are provided
  ansible.builtin.assert:
    that:
      - olam_secret_key is defined and olam_secret_key | length >= 16
      - olam_admin_password is defined and olam_admin_password | length >= 8

- name: Install depencies
  ansible.builtin.include_tasks: dependencies.yml
  tags: dependencies

- name: Install OLAM
  ansible.builtin.include_tasks: install.yml
  tags: install

- name: Configure OLAM
  ansible.builtin.include_tasks: config.yml
  tags: config

- name: Install awxkit
  ansible.builtin.include_tasks: awxkit.yml
  when: olam_install_awxkit | bool
