---

- name: deitkrachten.firewalld
  src: https://github.com/de-it-krachten/ansible-role-firewalld.git
  version: main
  scm: git
- name: deitkrachten.firewall
  src: https://github.com/de-it-krachten/ansible-role-firewall.git
  version: main
  scm: git
- name: deitkrachten.openssl
  src: https://github.com/de-it-krachten/ansible-role-openssl.git
  version: main
  scm: git
- name: deitkrachten.postgresql
  src: https://github.com/de-it-krachten/ansible-role-postgresql.git
  version: main
  scm: git
- name: deitkrachten.python
  src: https://github.com/de-it-krachten/ansible-role-python.git
  version: main
  scm: git
- name: deitkrachten.redis
  src: https://github.com/de-it-krachten/ansible-role-redis.git
  version: main
  scm: git
