---

- name: Dnf update cache
  ansible.builtin.dnf:
    update_cache: yes

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Restart postgresql
  ansible.builtin.service:
    name: postgresql
    state: restarted
