---

- name: Converge
  hosts: all
  become: "yes"
  vars:
    olam_db_external: True
    olam_disable_ipv6: True
    python38: False
    python39: False
    python311: False
  tasks:
    - name: Include role 'ansible-role-olam'
      ansible.builtin.include_role:
        name: ansible-role-olam
